### ISSUE TITLE
Sempai or Senpai?

### ISSUE THREAD

**Issue by d6e** [kragniz/json-sempai#16]
Isn't the canonical spelling "Senpai"?

Example:
![senpai](https://i.imgur.com/pFH2kYz.jpg)

**Comment by nekorug** [comment]
I'm by far no expert on this, so take this with a grain of salt:

There's no one "canonical" way to romanize Japanese. The only "correct" way of spelling sempai is 先輩. In the International Phonetic Alphabet, which is arguably the closes you can get to an objective spelling in roman characters, you would spell it [sẽ̞mpa̠i]. The issue is that the hiragana ん can sound either like "n", "ng", or "m" depending on the sound that follows, but as far as I'm aware most modern romanization pretty much always translate it as an "n" regardless of that context. Using "m" instead, in sempai for example, is more accurate to how it's pronounced, so that might be a reason to prefer it.

**Comment by d6e** [comment]
Ah, I always wondered why some people use 'm'. I stand corrected. :)
